apiVersion: v1
kind: ConfigMap
metadata:
  name: workshop-web
data:
  index.html: |
    <html>
      <body>
        <h1>My Kubernetes Application</h1>
        <p>Hello from Kubernetes!</p>
        <p>Configuration comes from a ConfigMap.</p>
      </body>
    </html>