apiVersion: v1
kind: Secret
metadata:
  name: workshop-web
type: Opaque

# Values im Klartext
stringData:
  workshop-user: student
  workshop-password: kubernetes

# Values mit Base64 codiert
# data:
#   workshop-user: c3R1ZGVudA==
#   workshop-password: a3ViZXJuZXRlcw==