apiVersion: icp4a.ibm.com/v1
kind: WfPSRuntime
metadata:
  name: wfps-instance1
spec:
  appVersion: "25.0.0"
  deploymentLicense: non-production
  license:
    accept: true
  admin:
    username: "cpadmin"
  persistent:
    storageClassName: "huaweisc"
